version: '2'

networks:
  test:

services:

  ca_diggipet:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.diggipet.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:
      - ./fabric-ca/diggipet:/etc/hyperledger/fabric-ca-server
    container_name: ca.diggipet.example.com
    hostname: ca.diggipet.example.com
    networks:
      - test