Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Diggipet
        Name: DiggipetMSP
        ID: DiggipetMSP

        MSPDir: ../../setup1/vm1/crypto-config/peerOrganizations/diggipet.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DiggipetMSP.admin', 'DiggipetMSP.peer', 'DiggipetMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DiggipetMSP.admin', 'DiggipetMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DiggipetMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DiggipetMSP.peer')"

        AnchorPeers:
            - Host: peer0.diggipet.example.com
              Port: 7051

    - &Vet_org
        Name: VetorgMSP

        ID: VetorgMSP

        MSPDir: ../../setup1/vm2/crypto-config/peerOrganizations/vet_org.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('VetorgMSP.admin', 'VetorgMSP.peer', 'VetorgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('VetorgMSP.admin', 'VetorgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('VetorgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('VetorgMSP.peer')"

        AnchorPeers:
            - Host: peer0.vet_org.example.com
              Port: 9051

    - &Breeders_org
        Name: BreedersorgMSP

        ID: BreedersorgMSP

        MSPDir: ../../setup1/vm3/crypto-config/peerOrganizations/breeders_org.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('BreedersorgMSP.admin', 'BreedersorgMSP.peer', 'BreedersorgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('BreedersorgMSP.admin', 'BreedersorgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('BreedersorgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('BreedersorgMSP.peer')"

        AnchorPeers:
            - Host: peer0.breeders_org.example.com
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: etcdraft

    EtcdRaft:
        Consenters:
        - Host: diggipet_orderer.example.com
          Port: 7050
          ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/diggipet_orderer.example.com/tls/server.crt
          ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/diggipet_orderer.example.com/tls/server.crt
    Addresses:
        - diggipet_orderer.example.com:7050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    BasicChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Diggipet
                - *Vet_org
                - *Breeders_org
            Capabilities:
                <<: *ApplicationCapabilities

    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: diggipet_orderer.example.com
                  Port: 7050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/diggipet_orderer.example.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/diggipet_orderer.example.com/tls/server.crt
                - Host: vet_orderer.example.com
                  Port: 8050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/vet_orderer.example.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/vet_orderer.example.com/tls/server.crt
                - Host: breeders_orderer.example.com
                  Port: 9050
                  ClientTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/breeders_orderer.example.com/tls/server.crt
                  ServerTLSCert: ../../setup1/vm4/crypto-config/ordererOrganizations/example.com/orderers/breeders_orderer.example.com/tls/server.crt
            Addresses:
                - diggipet_orderer.example.com:7050
                - vet_orderer.example.com:8050
                - breeders_orderer.example.com:9050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Diggipet
                - *Vet_org
                - *Breeders_org
