
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true

    Specs:
      - Hostname: diggipet_orderer
        SANS:
            - "localhost"
            - "127.0.0.1"
      - Hostname: vet_orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: breeders_orderer
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: Diggipet
    Domain: diggipet.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Vet_org
    Domain: vet_org.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: Breeders_org
    Domain: breeders_org.example.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1